### PR TITLE
ipmi: use efiboot option in ipmi pxe commands when required

### PR DESCRIPTION
**Pull request by gemagomez**
This change fixes the ipmi pxe command when efiboot option is required. 

Subarch now has a new field that determines whether this option will be added to the command or not. 

Fixes: #82

### CODE REVIEW

**Comment by LGraemeG** [comment]
With my small knowledge of python this looks like it is correct.

**Comment by rengolin** [comment]
The code looks ok apart from the part where it replaces class usage with pure SQL commands. A change in the sub-arch should have no impact on the Arch and should not need to demote internal logic to helpers.

**Comment by gemagomez** [comment]
@rengolin, that code that now has pure SQL command was wrong before. That is a DB upgrade and those are supposed not to use the DB model that they are trying to upgrade. That was a bug that we trip over when running travis tests: that particular upgrade failed and that part had to be rewritten to be future proof and make the database upgradable.

**Comment by bwalex** [comment]
@rengolin, as @gemagomez mentioned, there are good reasons to do it that way. If you load the ORM parts of sqlalchemy in migrations, you can run into nasty issues where you cannot actually do a migration because a field might be required/present in the ORM layer, but not (yet) in the database. Hence the removal of the ORM usage from the migration.

**Pull request merged**
